name: Docker Build and Push

on:
  push:
    branches:
      - master  # sadece master branch'ine push yapıldığında çalışacak

jobs:
  build:
    runs-on: ubuntu-latest  # işlem Ubuntu üzerinde çalışacak

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # `actions/checkout@v3` versiyonunu kullanıyoruz

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1  # Buildx ayarlarını yapıyoruz

      - name: Cache Docker layers
        uses: actions/cache@v3  # `actions/cache@v3` kullanıyoruz
        with:
          path: /tmp/.buildx-cache  # Docker cache konumunu belirtiyoruz
          key: ${{ runner.os }}-buildx-${{ github.sha }}  # Key belirliyoruz
          restore-keys: |
            ${{ runner.os }}-buildx-  # Cache restore anahtarı

      - name: Login to DockerHub
        uses: docker/login-action@v2  # DockerHub'a giriş yapıyoruz
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # DockerHub kullanıcı adımız
          password: ${{ secrets.DOCKER_PASSWORD }}  # DockerHub şifremiz veya token'ımız

      - name: Build and push Backend Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/mytodo-backend:v1 ./backend
          docker push ${{ secrets.DOCKER_USERNAME }}/mytodo-backend:v1

      - name: Build and push Frontend Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/mytodo-frontend:v1 ./frontend
          docker push ${{ secrets.DOCKER_USERNAME }}/mytodo-frontend:v1

